name: mysql
dependencies:
  build_native: ^0.0.7
  #build_native:
  #  path: ../build_native/build_native
  tuple: ^1.0.0
dev_dependencies:
  build_runner:
    git:
      url: https://github.com/thosakwe/build.git
      path: build_runner